export interface Work {
  title: string
  author: string
  type: 'book' | 'talk' | 'podcast' | 'article'
  year: number
  url?: string
}

export const CONTENT_LIBRARY: Record<string, Work[]> = {
  'Mind & Body': [
    { title: 'Why We Sleep', author: 'Matthew Walker', type: 'book', year: 2017 },
    { title: 'Outlive', author: 'Peter Attia', type: 'book', year: 2023 },
    { title: 'The Body Keeps the Score', author: 'Bessel van der Kolk', type: 'book', year: 2014 },
    { title: 'Being Mortal', author: 'Atul Gawande', type: 'book', year: 2014 },
    { title: 'Breath', author: 'James Nestor', type: 'book', year: 2020 },
    { title: 'Lifespan', author: 'David Sinclair', type: 'book', year: 2019 },
    { title: 'The Body', author: 'Bill Bryson', type: 'book', year: 2019 },
    { title: 'Spark', author: 'John Ratey', type: 'book', year: 2008 },
    { title: 'In Defense of Food', author: 'Michael Pollan', type: 'book', year: 2008 },
    { title: 'The Comfort Crisis', author: 'Michael Easter', type: 'book', year: 2021 },
    { title: 'The Brain That Changes Itself', author: 'Norman Doidge', type: 'book', year: 2007 },
    { title: 'When the Body Says No', author: 'Gabor Maté', type: 'book', year: 2003 },
    { title: 'Lost Connections', author: 'Johann Hari', type: 'book', year: 2018 },
    { title: 'How Not to Die', author: 'Michael Greger', type: 'book', year: 2015 },
    { title: 'The Blue Zones', author: 'Dan Buettner', type: 'book', year: 2008 },
    { title: 'Exercised', author: 'Daniel Lieberman', type: 'book', year: 2020 },
    { title: 'Good Energy', author: 'Casey Means', type: 'book', year: 2024 },
    { title: 'How to Change Your Mind', author: 'Michael Pollan', type: 'book', year: 2018 },
    { title: 'The Telomere Effect', author: 'Elizabeth Blackburn', type: 'book', year: 2017 },
    { title: 'The Happiness Advantage', author: 'Shawn Achor', type: 'book', year: 2010 },
    { title: 'How to Make Stress Your Friend', author: 'Kelly McGonigal', type: 'talk', year: 2013, url: 'https://www.youtube.com/watch?v=RcGyVTAoXEU' },
    { title: 'Sleep Is Your Superpower', author: 'Matt Walker', type: 'talk', year: 2019, url: 'https://www.youtube.com/watch?v=5MuIMqhT8pM' },
    { title: 'Huberman Lab', author: 'Andrew Huberman', type: 'podcast', year: 2021, url: 'https://open.spotify.com/show/79CkJF3UJTHFV8Dse3Oy0P' },
  ],

  'Habits': [
    { title: 'Atomic Habits', author: 'James Clear', type: 'book', year: 2018 },
    { title: 'The Power of Habit', author: 'Charles Duhigg', type: 'book', year: 2012 },
    { title: 'Deep Work', author: 'Cal Newport', type: 'book', year: 2016 },
    { title: 'Tiny Habits', author: 'BJ Fogg', type: 'book', year: 2019 },
    { title: 'The 7 Habits of Highly Effective People', author: 'Stephen Covey', type: 'book', year: 1989 },
    { title: 'Four Thousand Weeks', author: 'Oliver Burkeman', type: 'book', year: 2021 },
    { title: 'Essentialism', author: 'Greg McKeown', type: 'book', year: 2014 },
    { title: 'Getting Things Done', author: 'David Allen', type: 'book', year: 2001 },
    { title: 'Peak', author: 'Anders Ericsson', type: 'book', year: 2016 },
    { title: 'Grit', author: 'Angela Duckworth', type: 'book', year: 2016 },
    { title: 'Indistractable', author: 'Nir Eyal', type: 'book', year: 2019 },
    { title: 'Good Habits, Bad Habits', author: 'Wendy Wood', type: 'book', year: 2019 },
    { title: 'Ultralearning', author: 'Scott Young', type: 'book', year: 2019 },
    { title: 'Digital Minimalism', author: 'Cal Newport', type: 'book', year: 2019 },
    { title: 'The One Thing', author: 'Gary Keller', type: 'book', year: 2013 },
    { title: 'Make Time', author: 'Jake Knapp', type: 'book', year: 2018 },
    { title: 'Willpower', author: 'Roy Baumeister', type: 'book', year: 2011 },
    { title: 'Daily Rituals', author: 'Mason Currey', type: 'book', year: 2013 },
    { title: 'The Compound Effect', author: 'Darren Hardy', type: 'book', year: 2010 },
    { title: 'The Miracle Morning', author: 'Hal Elrod', type: 'book', year: 2012 },
    { title: 'Inside the Mind of a Master Procrastinator', author: 'Tim Urban', type: 'talk', year: 2016, url: 'https://www.youtube.com/watch?v=arj7oStGLkU' },
    { title: 'Grit: The Power of Passion and Perseverance', author: 'Angela Duckworth', type: 'talk', year: 2013, url: 'https://www.youtube.com/watch?v=H14bBuluwB8' },
    { title: 'The Power of Believing That You Can Improve', author: 'Carol Dweck', type: 'talk', year: 2014, url: 'https://www.youtube.com/watch?v=_X0mgOOSpLU' },
    { title: 'The Tim Ferriss Show', author: 'Tim Ferriss', type: 'podcast', year: 2014, url: 'https://open.spotify.com/show/5qSUyCrk9KR69lEiXbjwXM' },
  ],

  'Money': [
    { title: 'The Psychology of Money', author: 'Morgan Housel', type: 'book', year: 2020 },
    { title: 'The Intelligent Investor', author: 'Benjamin Graham', type: 'book', year: 1949 },
    { title: 'Rich Dad Poor Dad', author: 'Robert Kiyosaki', type: 'book', year: 1997 },
    { title: 'A Random Walk Down Wall Street', author: 'Burton Malkiel', type: 'book', year: 1973 },
    { title: 'Die With Zero', author: 'Bill Perkins', type: 'book', year: 2020 },
    { title: 'The Millionaire Next Door', author: 'Thomas Stanley', type: 'book', year: 1996 },
    { title: 'I Will Teach You to Be Rich', author: 'Ramit Sethi', type: 'book', year: 2009 },
    { title: 'The Little Book of Common Sense Investing', author: 'John Bogle', type: 'book', year: 2007 },
    { title: 'Principles', author: 'Ray Dalio', type: 'book', year: 2017 },
    { title: 'The Simple Path to Wealth', author: 'JL Collins', type: 'book', year: 2016 },
    { title: 'Your Money or Your Life', author: 'Vicki Robin', type: 'book', year: 1992 },
    { title: 'The Richest Man in Babylon', author: 'George S. Clason', type: 'book', year: 1926 },
    { title: 'Think and Grow Rich', author: 'Napoleon Hill', type: 'book', year: 1937 },
    { title: 'Common Stocks and Uncommon Profits', author: 'Philip Fisher', type: 'book', year: 1958 },
    { title: 'Flash Boys', author: 'Michael Lewis', type: 'book', year: 2014 },
    { title: 'When Genius Failed', author: 'Roger Lowenstein', type: 'book', year: 2000 },
    { title: 'Capital in the Twenty-First Century', author: 'Thomas Piketty', type: 'book', year: 2013 },
    { title: 'The Total Money Makeover', author: 'Dave Ramsey', type: 'book', year: 2003 },
    { title: 'The Automatic Millionaire', author: 'David Bach', type: 'book', year: 2003 },
    { title: 'Thinking in Bets', author: 'Annie Duke', type: 'book', year: 2018 },
    { title: 'Planet Money', author: 'NPR', type: 'podcast', year: 2008, url: 'https://open.spotify.com/show/4FYpq3lSeQMAhqNI81O0Cn' },
    { title: 'How to Make Wealth', author: 'Paul Graham', type: 'article', year: 2004, url: 'https://paulgraham.com/wealth.html' },
  ],

  'Relationships': [
    { title: 'Attached', author: 'Amir Levine', type: 'book', year: 2010 },
    { title: 'The Seven Principles for Making Marriage Work', author: 'John Gottman', type: 'book', year: 1999 },
    { title: 'How to Win Friends and Influence People', author: 'Dale Carnegie', type: 'book', year: 1936 },
    { title: 'Mating in Captivity', author: 'Esther Perel', type: 'book', year: 2006 },
    { title: 'The 5 Love Languages', author: 'Gary Chapman', type: 'book', year: 1992 },
    { title: 'Daring Greatly', author: 'Brené Brown', type: 'book', year: 2012 },
    { title: 'Hold Me Tight', author: 'Sue Johnson', type: 'book', year: 2008 },
    { title: 'The State of Affairs', author: 'Esther Perel', type: 'book', year: 2017 },
    { title: 'Why Does He Do That?', author: 'Lundy Bancroft', type: 'book', year: 2002 },
    { title: 'Come As You Are', author: 'Emily Nagoski', type: 'book', year: 2015 },
    { title: 'The Art of Loving', author: 'Erich Fromm', type: 'book', year: 1956 },
    { title: 'All About Love', author: 'bell hooks', type: 'book', year: 2000 },
    { title: 'Boundaries', author: 'Henry Cloud', type: 'book', year: 1992 },
    { title: 'Getting the Love You Want', author: 'Harville Hendrix', type: 'book', year: 1988 },
    { title: 'The Dance of Anger', author: 'Harriet Lerner', type: 'book', year: 1985 },
    { title: 'Never Split the Difference', author: 'Chris Voss', type: 'book', year: 2016 },
    { title: 'Models', author: 'Mark Manson', type: 'book', year: 2011 },
    { title: 'Captivate', author: 'Vanessa Van Edwards', type: 'book', year: 2017 },
    { title: 'The Course of Love', author: 'Alain de Botton', type: 'book', year: 2016 },
    { title: 'The Like Switch', author: 'Jack Schafer', type: 'book', year: 2015 },
    { title: 'The Power of Vulnerability', author: 'Brené Brown', type: 'talk', year: 2010, url: 'https://www.youtube.com/watch?v=iCvmsMzlF7o' },
    { title: 'The Secret to Desire in a Long-term Relationship', author: 'Esther Perel', type: 'talk', year: 2013, url: 'https://www.youtube.com/watch?v=sa0RUmGTCYY' },
    { title: 'What Makes a Good Life? Lessons from the Longest Study on Happiness', author: 'Robert Waldinger', type: 'talk', year: 2015, url: 'https://www.youtube.com/watch?v=8KkKuTCFvzI' },
    { title: 'Where Should We Begin?', author: 'Esther Perel', type: 'podcast', year: 2017, url: 'https://open.spotify.com/show/2WpeLETy4lIlLafeRgMJSg' },
  ],

  'Big Ideas': [
    { title: 'Sapiens', author: 'Yuval Noah Harari', type: 'book', year: 2011 },
    { title: "Man's Search for Meaning", author: 'Viktor Frankl', type: 'book', year: 1946 },
    { title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', type: 'book', year: 2011 },
    { title: 'Meditations', author: 'Marcus Aurelius', type: 'book', year: 180 },
    { title: 'The Denial of Death', author: 'Ernest Becker', type: 'book', year: 1973 },
    { title: 'Antifragile', author: 'Nassim Nicholas Taleb', type: 'book', year: 2012 },
    { title: 'The Black Swan', author: 'Nassim Nicholas Taleb', type: 'book', year: 2007 },
    { title: 'Homo Deus', author: 'Yuval Noah Harari', type: 'book', year: 2015 },
    { title: 'Gödel, Escher, Bach', author: 'Douglas Hofstadter', type: 'book', year: 1979 },
    { title: 'The Structure of Scientific Revolutions', author: 'Thomas Kuhn', type: 'book', year: 1962 },
    { title: 'The Selfish Gene', author: 'Richard Dawkins', type: 'book', year: 1976 },
    { title: 'The Myth of Sisyphus', author: 'Albert Camus', type: 'book', year: 1942 },
    { title: 'Thus Spoke Zarathustra', author: 'Friedrich Nietzsche', type: 'book', year: 1883 },
    { title: 'The Order of Time', author: 'Carlo Rovelli', type: 'book', year: 2017 },
    { title: '21 Lessons for the 21st Century', author: 'Yuval Noah Harari', type: 'book', year: 2018 },
    { title: 'Beyond Good and Evil', author: 'Friedrich Nietzsche', type: 'book', year: 1886 },
    { title: 'The Second Sex', author: 'Simone de Beauvoir', type: 'book', year: 1949 },
    { title: 'The Tao Te Ching', author: 'Laozi', type: 'book', year: -400 },
    { title: 'Simulacra and Simulation', author: 'Jean Baudrillard', type: 'book', year: 1981 },
    { title: 'A Brief History of Time', author: 'Stephen Hawking', type: 'book', year: 1988 },
    { title: 'The Danger of a Single Story', author: 'Chimamanda Ngozi Adichie', type: 'talk', year: 2009, url: 'https://www.youtube.com/watch?v=D9Ihs241zeg' },
    { title: 'Do Schools Kill Creativity?', author: 'Ken Robinson', type: 'talk', year: 2006, url: 'https://www.youtube.com/watch?v=iG9CE55wbtY' },
    { title: 'This Is Water', author: 'David Foster Wallace', type: 'article', year: 2005, url: 'https://fs.blog/david-foster-wallace-this-is-water/' },
    { title: 'Revisionist History', author: 'Malcolm Gladwell', type: 'podcast', year: 2016, url: 'https://open.spotify.com/show/5t7reWCp2TvXRVpkIYjaBK' },
  ],

  'How the World Works': [
    { title: 'Guns, Germs, and Steel', author: 'Jared Diamond', type: 'book', year: 1997 },
    { title: 'Why Nations Fail', author: 'Daron Acemoglu', type: 'book', year: 2012 },
    { title: 'The Power Broker', author: 'Robert Caro', type: 'book', year: 1974 },
    { title: 'Freakonomics', author: 'Steven Levitt', type: 'book', year: 2005 },
    { title: 'Thinking in Systems', author: 'Donella Meadows', type: 'book', year: 2008 },
    { title: "The Dictator's Handbook", author: 'Bruce Bueno de Mesquita', type: 'book', year: 2011 },
    { title: 'How Democracies Die', author: 'Steven Levitsky', type: 'book', year: 2018 },
    { title: 'On Tyranny', author: 'Timothy Snyder', type: 'book', year: 2017 },
    { title: 'The Shock Doctrine', author: 'Naomi Klein', type: 'book', year: 2007 },
    { title: 'Prisoners of Geography', author: 'Tim Marshall', type: 'book', year: 2015 },
    { title: 'Behave', author: 'Robert Sapolsky', type: 'book', year: 2017 },
    { title: 'The Origins of Political Order', author: 'Francis Fukuyama', type: 'book', year: 2011 },
    { title: 'The Anatomy of Fascism', author: 'Robert Paxton', type: 'book', year: 2004 },
    { title: 'Team of Rivals', author: 'Doris Kearns Goodwin', type: 'book', year: 2005 },
    { title: 'The Art of War', author: 'Sun Tzu', type: 'book', year: -500 },
    { title: 'The Prince', author: 'Niccolò Machiavelli', type: 'book', year: 1532 },
    { title: 'Upheaval', author: 'Jared Diamond', type: 'book', year: 2019 },
    { title: 'The Looming Tower', author: 'Lawrence Wright', type: 'book', year: 2006 },
    { title: 'The Road to Serfdom', author: 'Friedrich Hayek', type: 'book', year: 1944 },
    { title: 'Capital in the Twenty-First Century', author: 'Thomas Piketty', type: 'book', year: 2013 },
    { title: 'The Best Stats You\'ve Ever Seen', author: 'Hans Rosling', type: 'talk', year: 2006, url: 'https://www.youtube.com/watch?v=hVimVzgtD6w' },
    { title: 'Hardcore History', author: 'Dan Carlin', type: 'podcast', year: 2006, url: 'https://open.spotify.com/show/72qiPaoDRf8HkGKEChvG5q' },
    { title: 'Freakonomics Radio', author: 'Stephen Dubner', type: 'podcast', year: 2010, url: 'https://open.spotify.com/show/6z4NLXyHPga1UmSJsPK7G1' },
    { title: 'The Case for Reparations', author: 'Ta-Nehisi Coates', type: 'article', year: 2014, url: 'https://www.theatlantic.com/magazine/archive/2014/06/the-case-for-reparations/361631/' },
  ],

  'Science': [
    { title: 'A Brief History of Time', author: 'Stephen Hawking', type: 'book', year: 1988 },
    { title: 'The Selfish Gene', author: 'Richard Dawkins', type: 'book', year: 1976 },
    { title: 'The Gene', author: 'Siddhartha Mukherjee', type: 'book', year: 2016 },
    { title: 'Cosmos', author: 'Carl Sagan', type: 'book', year: 1980 },
    { title: 'The Emperor of All Maladies', author: 'Siddhartha Mukherjee', type: 'book', year: 2010 },
    { title: 'The Elegant Universe', author: 'Brian Greene', type: 'book', year: 1999 },
    { title: "Surely You're Joking, Mr. Feynman!", author: 'Richard Feynman', type: 'book', year: 1985 },
    { title: 'On the Origin of Species', author: 'Charles Darwin', type: 'book', year: 1859 },
    { title: 'The Sixth Extinction', author: 'Elizabeth Kolbert', type: 'book', year: 2014 },
    { title: 'The Order of Time', author: 'Carlo Rovelli', type: 'book', year: 2017 },
    { title: 'Astrophysics for People in a Hurry', author: 'Neil deGrasse Tyson', type: 'book', year: 2017 },
    { title: 'The Information', author: 'James Gleick', type: 'book', year: 2011 },
    { title: 'Your Inner Fish', author: 'Neil Shubin', type: 'book', year: 2008 },
    { title: 'The Demon-Haunted World', author: 'Carl Sagan', type: 'book', year: 1995 },
    { title: 'Genome', author: 'Matt Ridley', type: 'book', year: 1999 },
    { title: 'The Double Helix', author: 'James Watson', type: 'book', year: 1968 },
    { title: 'Lab Girl', author: 'Hope Jahren', type: 'book', year: 2016 },
    { title: 'The Hidden Life of Trees', author: 'Peter Wohlleben', type: 'book', year: 2015 },
    { title: 'What Is Life?', author: 'Erwin Schrödinger', type: 'book', year: 1944 },
    { title: 'The Structure of Scientific Revolutions', author: 'Thomas Kuhn', type: 'book', year: 1962 },
    { title: 'Your Brain Hallucinates Your Conscious Reality', author: 'Anil Seth', type: 'talk', year: 2017, url: 'https://www.youtube.com/watch?v=lyu7v7nWzfo' },
    { title: 'Radiolab', author: 'Jad Abumrad', type: 'podcast', year: 2002, url: 'https://open.spotify.com/show/2hmkzUtix0qTqvUSxCCRMd' },
    { title: 'The Uninhabitable Earth', author: 'David Wallace-Wells', type: 'article', year: 2017, url: 'https://nymag.com/intelligencer/2017/07/climate-change-earth-too-hot-for-humans.html' },
  ],

  'Cooking': [
    { title: "The Omnivore's Dilemma", author: 'Michael Pollan', type: 'book', year: 2006 },
    { title: 'Salt, Fat, Acid, Heat', author: 'Samin Nosrat', type: 'book', year: 2017 },
    { title: 'Kitchen Confidential', author: 'Anthony Bourdain', type: 'book', year: 2000 },
    { title: 'On Food and Cooking', author: 'Harold McGee', type: 'book', year: 1984 },
    { title: 'The Food Lab', author: 'J. Kenji López-Alt', type: 'book', year: 2015 },
    { title: 'Mastering the Art of French Cooking', author: 'Julia Child', type: 'book', year: 1961 },
    { title: 'An Everlasting Meal', author: 'Tamar Adler', type: 'book', year: 2011 },
    { title: 'The Flavor Bible', author: 'Karen Page', type: 'book', year: 2008 },
    { title: 'Cooked', author: 'Michael Pollan', type: 'book', year: 2013 },
    { title: 'Heat', author: 'Bill Buford', type: 'book', year: 2006 },
    { title: 'The Art of Simple Food', author: 'Alice Waters', type: 'book', year: 2007 },
    { title: 'Consider the Fork', author: 'Bee Wilson', type: 'book', year: 2012 },
    { title: 'Blood, Bones & Butter', author: 'Gabrielle Hamilton', type: 'book', year: 2011 },
    { title: 'Medium Raw', author: 'Anthony Bourdain', type: 'book', year: 2010 },
    { title: 'The Botany of Desire', author: 'Michael Pollan', type: 'book', year: 2001 },
    { title: 'In Defense of Food', author: 'Michael Pollan', type: 'book', year: 2008 },
    { title: 'Fat Chance', author: 'Robert Lustig', type: 'book', year: 2012 },
    { title: 'The End of Overeating', author: 'David Kessler', type: 'book', year: 2009 },
    { title: 'The French Laundry Cookbook', author: 'Thomas Keller', type: 'book', year: 1999 },
    { title: 'Nose to Tail Eating', author: 'Fergus Henderson', type: 'book', year: 1999 },
    { title: 'Gastropod', author: 'Nicola Twilley & Cynthia Graber', type: 'podcast', year: 2014, url: 'https://open.spotify.com/show/3Ex1KvAaFq4VhOlvIBUUPK' },
  ],

  'Leisure': [
    { title: 'The Creative Act', author: 'Rick Rubin', type: 'book', year: 2023 },
    { title: "The Artist's Way", author: 'Julia Cameron', type: 'book', year: 1992 },
    { title: 'The War of Art', author: 'Steven Pressfield', type: 'book', year: 2002 },
    { title: 'Ways of Seeing', author: 'John Berger', type: 'book', year: 1972 },
    { title: 'On Photography', author: 'Susan Sontag', type: 'book', year: 1977 },
    { title: 'The Rest Is Noise', author: 'Alex Ross', type: 'book', year: 2007 },
    { title: 'This Is Your Brain on Music', author: 'Daniel J. Levitin', type: 'book', year: 2006 },
    { title: 'Born to Run', author: 'Bruce Springsteen', type: 'book', year: 2016 },
    { title: 'Story', author: 'Robert McKee', type: 'book', year: 1997 },
    { title: 'Just Kids', author: 'Patti Smith', type: 'book', year: 2010 },
    { title: 'In Patagonia', author: 'Bruce Chatwin', type: 'book', year: 1977 },
    { title: 'A Year in Provence', author: 'Peter Mayle', type: 'book', year: 1989 },
    { title: 'Eat, Pray, Love', author: 'Elizabeth Gilbert', type: 'book', year: 2006 },
    { title: 'What I Talk About When I Talk About Running', author: 'Haruki Murakami', type: 'book', year: 2007 },
    { title: 'Leonardo da Vinci', author: 'Walter Isaacson', type: 'book', year: 2017 },
    { title: 'Zen and the Art of Motorcycle Maintenance', author: 'Robert Pirsig', type: 'book', year: 1974 },
    { title: 'The Motorcycle Diaries', author: 'Ernesto Che Guevara', type: 'book', year: 1995 },
    { title: 'Walden', author: 'Henry David Thoreau', type: 'book', year: 1854 },
    { title: 'Save the Cat!', author: 'Blake Snyder', type: 'book', year: 2005 },
    { title: 'Blue Highways', author: 'William Least Heat-Moon', type: 'book', year: 1982 },
    { title: 'Your Elusive Creative Genius', author: 'Elizabeth Gilbert', type: 'talk', year: 2009, url: 'https://www.youtube.com/watch?v=86x-u-tz0MA' },
    { title: '99% Invisible', author: 'Roman Mars', type: 'podcast', year: 2010, url: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM' },
    { title: 'Why I Write', author: 'George Orwell', type: 'article', year: 1946, url: 'https://www.orwell.ru/library/essays/wiw/english/e_wiw' },
  ],

  'Technology': [
    { title: 'The Innovators', author: 'Walter Isaacson', type: 'book', year: 2014 },
    { title: 'Zero to One', author: 'Peter Thiel', type: 'book', year: 2014 },
    { title: 'The Age of Surveillance Capitalism', author: 'Shoshana Zuboff', type: 'book', year: 2019 },
    { title: 'The Shallows', author: 'Nicholas Carr', type: 'book', year: 2010 },
    { title: 'Life 3.0', author: 'Max Tegmark', type: 'book', year: 2017 },
    { title: 'The Second Machine Age', author: 'Erik Brynjolfsson', type: 'book', year: 2014 },
    { title: 'Human Compatible', author: 'Stuart Russell', type: 'book', year: 2019 },
    { title: 'The Alignment Problem', author: 'Brian Christian', type: 'book', year: 2020 },
    { title: 'The Design of Everyday Things', author: 'Don Norman', type: 'book', year: 1988 },
    { title: 'Hackers', author: 'Steven Levy', type: 'book', year: 1984 },
    { title: 'Masters of Doom', author: 'David Kushner', type: 'book', year: 2003 },
    { title: 'No Filter', author: 'Sarah Frier', type: 'book', year: 2020 },
    { title: 'The Lean Startup', author: 'Eric Ries', type: 'book', year: 2011 },
    { title: 'Super Intelligence', author: 'Nick Bostrom', type: 'book', year: 2014 },
    { title: 'The Coming Wave', author: 'Mustafa Suleyman', type: 'book', year: 2023 },
    { title: 'Alone Together', author: 'Sherry Turkle', type: 'book', year: 2011 },
    { title: 'Code', author: 'Charles Petzold', type: 'book', year: 1999 },
    { title: 'Prediction Machines', author: 'Ajay Agrawal', type: 'book', year: 2018 },
    { title: 'Ghost in the Wires', author: 'Kevin Mitnick', type: 'book', year: 2011 },
    { title: 'The Facebook Effect', author: 'David Kirkpatrick', type: 'book', year: 2010 },
    { title: 'How a Handful of Tech Companies Control Billions of Minds', author: 'Tristan Harris', type: 'talk', year: 2017, url: 'https://www.youtube.com/watch?v=C74amJptB4I' },
    { title: 'Lex Fridman Podcast', author: 'Lex Fridman', type: 'podcast', year: 2018, url: 'https://open.spotify.com/show/2MAi0BvDc6GTFvKFPXnkCL' },
    { title: 'Hackers and Painters', author: 'Paul Graham', type: 'article', year: 2003, url: 'https://paulgraham.com/hp.html' },
  ],

  'Career': [
    { title: 'Good to Great', author: 'Jim Collins', type: 'book', year: 2001 },
    { title: 'The Hard Thing About Hard Things', author: 'Ben Horowitz', type: 'book', year: 2014 },
    { title: 'High Output Management', author: 'Andrew Grove', type: 'book', year: 1983 },
    { title: 'Start with Why', author: 'Simon Sinek', type: 'book', year: 2009 },
    { title: 'Radical Candor', author: 'Kim Scott', type: 'book', year: 2017 },
    { title: "So Good They Can't Ignore You", author: 'Cal Newport', type: 'book', year: 2012 },
    { title: 'Drive', author: 'Daniel Pink', type: 'book', year: 2009 },
    { title: 'The Effective Executive', author: 'Peter Drucker', type: 'book', year: 1967 },
    { title: 'Measure What Matters', author: 'John Doerr', type: 'book', year: 2018 },
    { title: 'Give and Take', author: 'Adam Grant', type: 'book', year: 2013 },
    { title: 'Shoe Dog', author: 'Phil Knight', type: 'book', year: 2016 },
    { title: 'The Checklist Manifesto', author: 'Atul Gawande', type: 'book', year: 2009 },
    { title: 'Turn the Ship Around!', author: 'L. David Marquet', type: 'book', year: 2013 },
    { title: 'Multipliers', author: 'Liz Wiseman', type: 'book', year: 2010 },
    { title: 'Leaders Eat Last', author: 'Simon Sinek', type: 'book', year: 2014 },
    { title: 'Never Split the Difference', author: 'Chris Voss', type: 'book', year: 2016 },
    { title: 'What Got You Here Won\'t Get You There', author: 'Marshall Goldsmith', type: 'book', year: 2007 },
    { title: 'The 4-Hour Workweek', author: 'Tim Ferriss', type: 'book', year: 2007 },
    { title: 'Thinking in Bets', author: 'Annie Duke', type: 'book', year: 2018 },
    { title: 'The $100 Startup', author: 'Chris Guillebeau', type: 'book', year: 2012 },
    { title: 'How Great Leaders Inspire Action', author: 'Simon Sinek', type: 'talk', year: 2009, url: 'https://www.youtube.com/watch?v=u4ZoJKF_VuA' },
    { title: 'The Puzzle of Motivation', author: 'Dan Pink', type: 'talk', year: 2009, url: 'https://www.youtube.com/watch?v=rrkrvAUbU9Y' },
    { title: 'How I Built This', author: 'Guy Raz', type: 'podcast', year: 2016, url: 'https://open.spotify.com/show/6E709HRH7XaiZrMfgtNCun' },
    { title: 'How to Do Great Work', author: 'Paul Graham', type: 'article', year: 2023, url: 'https://paulgraham.com/greatwork.html' },
  ],

  'Psychology': [
    { title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', type: 'book', year: 2011 },
    { title: 'Influence', author: 'Robert Cialdini', type: 'book', year: 1984 },
    { title: 'The Body Keeps the Score', author: 'Bessel van der Kolk', type: 'book', year: 2014 },
    { title: "Man's Search for Meaning", author: 'Viktor Frankl', type: 'book', year: 1946 },
    { title: 'Predictably Irrational', author: 'Dan Ariely', type: 'book', year: 2008 },
    { title: 'Behave', author: 'Robert Sapolsky', type: 'book', year: 2017 },
    { title: 'Flow', author: 'Mihaly Csikszentmihalyi', type: 'book', year: 1990 },
    { title: 'Stumbling on Happiness', author: 'Daniel Gilbert', type: 'book', year: 2006 },
    { title: 'Quiet', author: 'Susan Cain', type: 'book', year: 2012 },
    { title: 'Emotional Intelligence', author: 'Daniel Goleman', type: 'book', year: 1995 },
    { title: 'Blink', author: 'Malcolm Gladwell', type: 'book', year: 2005 },
    { title: 'The Paradox of Choice', author: 'Barry Schwartz', type: 'book', year: 2004 },
    { title: 'Misbehaving', author: 'Richard Thaler', type: 'book', year: 2015 },
    { title: 'The Lucifer Effect', author: 'Philip Zimbardo', type: 'book', year: 2007 },
    { title: 'Mistakes Were Made (But Not by Me)', author: 'Carol Tavris', type: 'book', year: 2007 },
    { title: 'Self-Compassion', author: 'Kristin Neff', type: 'book', year: 2011 },
    { title: 'The Willpower Instinct', author: 'Kelly McGonigal', type: 'book', year: 2011 },
    { title: 'Lost Connections', author: 'Johann Hari', type: 'book', year: 2018 },
    { title: 'The Power of Now', author: 'Eckhart Tolle', type: 'book', year: 1997 },
    { title: 'When Nietzsche Wept', author: 'Irvin D. Yalom', type: 'book', year: 1992 },
    { title: 'Are We in Control of Our Own Decisions?', author: 'Dan Ariely', type: 'talk', year: 2008, url: 'https://www.youtube.com/watch?v=9X68dm92HVI' },
    { title: 'The Power of Introverts', author: 'Susan Cain', type: 'talk', year: 2012, url: 'https://www.youtube.com/watch?v=c0KYU2j0TM4' },
    { title: 'Flow, the Secret to Happiness', author: 'Mihaly Csikszentmihalyi', type: 'talk', year: 2004, url: 'https://www.youtube.com/watch?v=fXIeFJCqsPs' },
    { title: 'Your Body Language May Shape Who You Are', author: 'Amy Cuddy', type: 'talk', year: 2012, url: 'https://www.youtube.com/watch?v=Ks-_Mh1QhMc' },
    { title: 'Hidden Brain', author: 'Shankar Vedantam', type: 'podcast', year: 2015, url: 'https://open.spotify.com/show/20Gf4IAauFrfj7RBkjcWxh' },
  ],
}
